#------------------------------------------------------------
# Magic Castle: Slurm + Software Stack from EESSI
#------------------------------------------------------------

# Cluster host and scheduler options: the defaults come from
# Graham at Compute Canada, running Slurm. Other options for
# other systems can be found in the library of snippets,
# `_includes/snippets_library`.
#
# Please refer to
# https://github.com/carpentries-incubator/hpc-intro#using-this-material
# in order to see how to include a specific set of snippets
# in your lesson and
# https://github.com/carpentries-incubator/hpc-intro#deploying-a-customized-lesson
# in order to see how to deploy a specific instance of a lesson.
#
# If your cluster is not represented in the library, please
# copy an existing folder, rename it, and customize for your
# installation. Remember to keep the leading slash on the
# `snippets` variable below!
#
# For this specific snippet library that uses Magic Castle (
# https://github.com/ComputeCanada/magic_castle/tree/master/docs#magic-castle-documentation
# ) with the EESSI (https://eessi.github.io/docs/) software
# stack you will most likely also need to provide a customised
# version of the cluster name and domain, which is currently
# set to
# "custom.learnhpc.eu".
# For example, if our cluster was called
# "cluster.hpc-carpentry.org", we could do this in a
# single `sed` command from the current directory:
# sed -i s/custom.learnhpc.eu/cluster.hpc-carpentry.org/g _config_options.yml

snippets: "/snippets_library/MSU_ICER_slurm"

local:
  prompt: "[user@laptop ~]$"
  bash_shebang: "#!/usr/bin/env bash"

remote:
  name: "ICER HPCC"
  login: "hpcc.msu.edu"
  host: "dev-amd20"
  node: "amr-252"
  location: "Michigan State University"
  homedir: "/mnt/home"
  user: "netid"
  module_python3: "GCC/10.2.0 OpenMPI/4.0.5 Python/3.8.6"
  prompt: "[netid@dev-amd20 ~]$"
  bash_shebang: "#!/usr/bin/env bash"
  mpirun: "srun"

sched:
  name: "Slurm"
  submit:
    name: "sbatch"
    options: ""
  queue:
    debug: "general-short"
    testing: "general-short"
  status: "squeue"
  flag:
    user: "-u netid"
    interactive: ""
    histdetail: "-l -j"
    name: "-J"
    time: "-t"
    queue: "-p"
  del: "scancel"
  interactive: "srun"
  info: "sinfo"
  comment: "#SBATCH"
  hist: "sacct -u netid"

episode_order:
  - 10-hpc-intro
  - 11-connecting
  - 12-cluster
  - 13-scheduler
  - 14-modules
  - 15-transferring-files
  - 16-parallel
  - 17-resources
  - 18-responsibility
